# -*- coding: utf-8 -*-
"""yash variables.ipynb.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dMVgcqxKr7PqgEad2iFlZVd_g7JfMcsX
"""

#1
name = "Yash jagtap"
print(name)

#2
age = 23
print(age)

#3
price = 22.99
quantity = 5
total_cost = price * quantity
print(total_cost)

#4
result = 8 + 7
print(result)

#5
X=10
Y=20
Z=X
X=Y
Y=Z
print("X:-",X)
print("Y:-",Y)

#6
favorite_color = "Saffron"
print(f"My favorite color is {favorite_color}")

#7
Student=True
Teacher=False
print(Student)

#8
A= 28.5757
B= round(A, 2)
print(B)

#9#
h= 1.80
w= 85
print(f"Height: {h} meters, Weight: {w} kg")